services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Utils\FileLoader\FileLoaderInterface:
        alias: App\Utils\FileLoader\JsonFileLoader

    App\Utils\FileLoader\JsonFileLoader:
        autowire: true
        autoconfigure: true

    App\Controller\Api\FoodController:
        tags: ['controller.service_arguments']

    App\Service\FoodServiceInterface:
        class: App\Service\FoodService
        public: true                     

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\Api\FoodImportController:
        arguments:
            $filePath: '%food_file_path%'

    App\Service\FoodCollectionProcessor:
        public: true                     

parameters:
    food_file_path: '%kernel.project_dir%/request.json' 
    
